version: '2'
services:

### MySQL ###############################################

  mysql:
    image: mysql:5.7
    container_name: epix-2.9.2-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
    labels:
      - "service-name:epix"
      - "service-type:db-srv"
      - "environment:test"    
      
### WildFly #############################################
  wildfly:
    image: mosaicgreifswald/wildfly:18.0.1.Final-20191213
    container_name: epix-2.9.2-wildfly
    links:
      - "mysql:mysqldb"
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      WILDFLY_PASS: wildfly_password      
      JAVA_OPTS: '-server -Xms1G -Xmx6G -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=1G -XX:StringTableSize=1000003 -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Djboss.modules.system.pkgs=org.jboss.byteman' 
    depends_on:
      - mysql
    volumes:
      - ./jboss:/entrypoint-jboss-batch
      - ./deployments:/entrypoint-deployments
    labels:
      - "service-name:epix"
      - "service-type:app-srv"
      - "environment:test"
    entrypoint: /bin/bash
    command: -c "./wait-for-it.sh mysql:3306 -t 120 && ./run.sh"
